# Generated by Django 4.2.13 on 2024-06-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_cloud_storage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
