apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: {{ .Values.google_app_creds.file_name }}-volume
          mountPath: {{ .Values.image.workdir }}/{{ .Values.google_app_creds.file_name }}
      volumes:
      - name: {{ .Values.google_app_creds.file_name }}-volume
        configMap:
          name: {{ .Values.google_app_creds.file_name }}-configmap