apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-{{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: google-cloud-sql-configmap
              key: postgresql-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: google-cloud-sql-secret
              key: postgresql-username
        - name: DB_PASS
          valueFrom: 
            secretKeyRef:
              name: google-cloud-sql-secret
              key: postgresql-password
        volumeMounts:
        - name: google-app-creds-volume
          mountPath: {{ .Values.image.workdir }}/google-app-creds
      volumes:
      - name: google-app-creds-volume
        configMap:
          name: google-app-creds-configmap